### ISSUE TITLE
Add support for Express 3.x

### ISSUE THREAD

**Issue by gvilarino** [paulomcnally/node-heroku-ssl-redirect#1]
[Usage of `req.hostname`](https://github.com/paulomcnally/node-heroku-ssl-redirect/blob/master/index.js#L11) implies `express` is version `4.x`. [In `3.x` the attribute is `host`](http://expressjs.com/3x/api.html#req.host) and thus redirection ends up going to `https://undefined` if not using `express@4.x`

**Comment by paulomcnally** [comment]
Please use https://github.com/paulomcnally/node-heroku-ssl-redirect#expressjs-3x-issue-1
