### ISSUE TITLE
TypeError: sslRedirect is not a function

### ISSUE THREAD

**Issue by N00nDay** [paulomcnally/node-heroku-ssl-redirect#17]
When upgrading from `0.0.4` to `0.1.1` my node server crashes and receives the error `TypeError: sslRedirect is not a function`. Downgraded back to `0.0.4` and works again.

**Comment by marr** [comment]
Same issue here

**Comment by marr** [comment]
@N00nDay It looks like the export was changed to be `default` (likely using ES6 modules). So you may be able to use the latest package, if you are using require instead of import, just:
`const sslRedirect = require('heroku-ssl-redirect').default`
That should fix things

**Comment by N00nDay** [comment]
Makes sense, thank you.

**Comment by pubmikeb** [comment]
I tried to use `import sslRedirect from 'heroku-ssl-redirect';` inside of ES Module (`.mjs`) but I'm still getting the same `TypeError: sslRedirect is not a function` error.

How can I resolve such error?

**Comment by clintgossett** [comment]
> @N00nDay It looks like the export was changed to be `default` (likely using ES6 modules). So you may be able to use the latest package, if you are using require instead of import, just:
> `const sslRedirect = require('heroku-ssl-redirect').default`
> That should fix things

Thank you, this worked for me.  @pubmikeb I had to use the above and the project back to .js...no module declaration.

**Comment by valentinoli** [comment]
Workaround if you want to use ES modules:

```js
import herokuSSLRedirect from 'heroku-ssl-redirect'
const sslRedirect = herokuSSLRedirect.default
```

**Comment by IgnacioGB1990** [comment]
Downgrading worked for me!

Run: **npm i heroku-ssl-redirect@0.0.4**
 
Thanks!
