### ISSUE TITLE
Question about seo

### ISSUE THREAD

**Issue by Gionni** [paulomcnally/node-heroku-ssl-redirect#3]
If I enable ssl on my heroku app after months of activity with few pages having reached a good ranking in google serp, does your package make 301 redirect similar to Apache .htaccess, in a way that ranking goes from old http page to new equal https page?

Thanks, Gionni

**Comment by paulomcnally** [comment]
* https://moz.com/learn/seo/redirection
* http://searchenginewatch.com/sew/how-to/2377744/your-guide-to-301-redirects-for-seo

**More:** https://goo.gl/nKrIql
